## Import required libraries

In [1]:
import numpy as np
import scipy as sp
from numpy.linalg import LinAlgError
from Test import ALG

## Parameters Dictionary

In [ ]:
class gen_param_dict(object):
    '''
    init: define the class constructor of with no arguments
    '''
    def __init__(self):
        print('Generating all parameters')
        
    def gen_param_ALG(self): # add args
        # Algorithm
        ALG = {
            'inner_iterations': 1,  # Number of iterations.
            'min_eta': 1e-5,        # Minimum initial lagrange multiplier in DGD for trajectory optimization.
            'kl_step':0.2,
            'min_step_mult':0.01,
            'max_step_mult':10.0,
            'min_mult': 0.1,
            'max_mult': 5.0,
            # Trajectory settings.
            'initial_state_var':1e-6,
            'init_traj_distr': None, # A list of initial LinearGaussianPolicy objects for each condition.
            # Trajectory optimization.
            'traj_opt': None,
            # Weight of maximum entropy term in trajectory optimization.
            'max_ent_traj': 0.0,
            # Dynamics hyperaparams.
            'dynamics': None,
            # Costs.
            'cost': None,  # A list of Cost objects for each condition.
            # Whether or not to sample with neural net policy (only for badmm/mdgps).
            'sample_on_policy': False,
            # Inidicates if the algorithm requires fitting of the dynamics.
            'fit_dynamics': True,    
        }
        return ALG
    
    def gen_param_ALG_BADMM(self): # add args
        # Algorithm BADMM
        ALG_BADMM = {
            'inner_iterations': 4,
            'policy_dual_rate': 0.1,
            'policy_dual_rate_covar': 0.0,
            'fixed_lg_step': 0,
            'lg_step_schedule': 10.0,
            'ent_reg_schedule': 0.0,
            'init_pol_wt': 0.01,
            'policy_sample_mode': 'add',
            'exp_step_increase': 2.0,
            'exp_step_decrease': 0.5,
            'exp_step_upper': 0.5,
            'exp_step_lower': 1.0,
        }
        return ALG_BADMM



## Required function class

In [ ]:
class param_hold(object):
    def __intit__(self, ALG_BADMM, ):
        sas

In [3]:
a = {
    'a': 1,
    
    'b': 2
}
print(a['b'])

2


In [2]:
# ALG['min_eta'] = 10
print(ALG)

{'inner_iterations': 1, 'min_eta': 1e-05, 'kl_step': 0.2, 'min_step_mult': 0.01, 'max_step_mult': 10.0, 'min_mult': 0.1, 'max_mult': 5.0, 'initial_state_var': 1e-06, 'init_traj_distr': None, 'traj_opt': None, 'max_ent_traj': 0.0, 'dynamics': None, 'cost': None, 'sample_on_policy': False, 'fit_dynamics': True}


In [4]:
# a x b = 2 x 3
# b x c = 3 x 4
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [11], [15]])
c = a - b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [11]:
# a x b = 2 x 3
# b x c = 1 x 3
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 81, 92]])
c = a - b
c = np.sum(c, axis=1, keepdims=True) # 2 x 1
print(a)
print(c)
print(a - c)

[[1 2 3]
 [4 5 6]]
[[-174]
 [-165]]
[[175 176 177]
 [169 170 171]]
