In [1]:
import numpy as np
import scipy as sp

In [7]:
dU = 2
dX = 12
acc = gains = np.ones(dU)
dt = 0.02

In [8]:
    Fd = np.vstack([
        np.hstack([
            np.eye(dU), dt * np.eye(dU), np.zeros((dU, dX - dU*2)),
            dt ** 2 * np.diag(gains)
        ]),
        np.hstack([
            np.zeros((dU, dU)), np.eye(dU), np.zeros((dU, dX - dU*2)),
            dt * np.diag(gains)
        ]),
        np.zeros((dX - dU*2, dX+dU))
    ])
    fc = np.hstack([acc * dt ** 2, acc * dt, np.zeros((dX - dU*2))])

In [9]:
Fd.shape

(12, 14)

In [10]:
np.hstack([
    np.eye(dU), dt * np.eye(dU), np.zeros((dU, dX - dU*2)),
    dt ** 2 * np.diag(gains)
])

array([[1.e+00, 0.e+00, 2.e-02, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00, 0.e+00, 0.e+00, 4.e-04, 0.e+00],
       [0.e+00, 1.e+00, 0.e+00, 2.e-02, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 4.e-04]])

In [11]:
(dt ** 2 * np.diag(gains)).shape

(2, 2)

In [12]:
np.zeros((dU, dX - dU*2)).shape

(2, 8)

In [13]:
np.hstack([
    np.zeros((dU, dU)), np.eye(dU), np.zeros((dU, dX - dU*2)),
    dt * np.diag(gains)
])

array([[0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.02, 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.02]])

In [14]:
np.diag(np.eye(5,5))

array([1., 1., 1., 1., 1.])

In [15]:
    Ltt = np.diag(np.hstack([
        1 * np.ones(dU),
        1 * 2 * np.ones(dU),
        np.zeros(dX - dU*2), np.ones(dU)
    ]))

In [17]:
Ltt.shape

(14, 14)

In [ ]:
np.hstack([
        1 * np.ones(dU),
        1 * 2 * np.ones(dU),
        np.zeros(dX - dU*2), np.ones(dU)
    ])

In [ ]:
x0 = np.ones(12)

In [ ]:
lt = -Ltt.dot(np.r_[x0, np.zeros(dU)])

In [ ]:
lt.shape

In [2]:
import scipy.linalg as linalg

array([[  6.        ,  40.61737691, 320.28098876],
       [  0.        ,  17.5       , 215.30193008],
       [  0.        ,   0.        ,  37.33333333]])